version: '3'
services:
  cloudbeaver:
    build: .
    container_name: sqle-cloudbeaver:22.2.0
    ports:
      - "8978:8978"
    volumes:
      - "./logs:/opt/cloudbeaver/logs"
      - "./workspace:/opt/cloudbeaver/workspace"
